### ISSUE TITLE
Comprobar ansible (hace falta modificar Vagrantfile)-IMPORTANTE LEER-

### ISSUE THREAD

**Issue by 22adrian22** [Almarchi/FTP-TEAM#1]
# 🚀 **Última Actualización:**  

Versión basada en **Vagrant (sin provisión)** y **Ansible** utilizando los archivos:  
- `site.yml`
- `ftp_playbook.yml`
- `inventory.yml`

---

## ⚠️ ADVERTENCIA  
Esta configuración necesita ser probada en clase.  
En pruebas locales en sistemas Windows, se han encontrado problemas relacionados con Ansible.

---

## 🎯 OBJETIVO  
Implementar una configuración en la que, al integrar los tres archivos de Ansible en el `Vagrantfile` y ejecutar `vagrant up` por primera vez, se ejecute automáticamente la provisión definida en los playbooks.  

Esto realizará automáticamente las siguientes tareas:

### **1. `site.yml`:**  
Configura el servidor **DNS** en la máquina `tierra` y establece los ajustes necesarios en las demás máquinas.  
- Instala **BIND9** y lo configura como servidor DNS.
- Copia los archivos de configuración (`named.conf.local`, `named.conf.options`) y las zonas DNS (`db.sistema.sol`, `db.192.168.57`).
- Reinicia y habilita el servicio DNS.
- Configura en las máquinas cliente (`mercurio`, `venus`, `marte`) el archivo `resolv.conf` para que apunten al servidor DNS de `tierra`.

### **2. `ftp_playbook.yml`:**  
Automatiza las tareas relacionadas con el **cliente FTP** en la máquina `tierra`.  
Para realizar automáticamente todas las tareas del apartado 2, es necesario usar manualmente el siguiente comando:  
```bash
ansible-playbook -i inventory.yml ftp_playbook.yml
```

- Crea el usuario `pepe` y el directorio `/home/pepe/pruebasFTP`.
- Genera el archivo `datos1.txt` con contenido personalizado.

### **3. `inventory.yml`:**  
Define los grupos de máquinas y sus respectivas direcciones IP:
- `tierra`: 192.168.57.103
- `clientes`: 192.168.57.101, 192.168.57.102, 192.168.57.104

---

## 🌐 FLUJO DE TRABAJO  

Con esta configuración, al ejecutar `vagrant up`:
1. **Servidor DNS**: Se configura correctamente en `tierra`, y las máquinas `mercurio`, `venus` y `marte` apuntan a él.
2. **Tareas FTP**: Acciones del cliente FTP iniciales que se ejecutan automáticamente en la máquina `tierra`, cubriendo parte del ejercicio.

---

### **1. Vagrantfile**
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "tierra" do |tierra|
    tierra.vm.hostname = "tierra.sistema.sol"
    tierra.vm.network :private_network, ip: "192.168.57.103"
  end

  config.vm.define "mercurio" do |mercurio|
    mercurio.vm.hostname = "mercurio.sistema.sol"
    mercurio.vm.network :private_network, ip: "192.168.57.101"
  end

  config.vm.define "venus" do |venus|
    venus.vm.hostname = "venus.sistema.sol"
    venus.vm.network :private_network, ip: "192.168.57.102"
  end

  config.vm.define "marte" do |marte|
    marte.vm.hostname = "marte.sistema.sol"
    marte.vm.network :private_network, ip: "192.168.57.104"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.inventory_path = "inventory.yml"
  end
end
```

### **2. ftp_playbook.yml**  
```yaml
- name: Uso del cliente FTP en línea de comandos
  hosts: tierra
  become: yes
  tasks:
    - name: Crear usuario pepe si no existe
      user:
        name: pepe
        state: present
        create_home: yes

    - name: Crear directorio /home/pepe/pruebasFTP
      file:
        path: /home/pepe/pruebasFTP
        state: directory
        owner: pepe
        group: pepe
        mode: '0755'

    - name: Cambiar al directorio pruebasFTP
      ansible.builtin.shell: cd /home/pepe/pruebasFTP

    - name: Crear archivo datos1.txt con contenido
      ansible.builtin.copy:
        content: |
          Este es un archivo de prueba para el FTP.
        dest: /home/pepe/pruebasFTP/datos1.txt
        owner: pepe
        group: pepe
        mode: '0644'
```

### **3. inventory.yml**
```ini
[tierra]
192.168.57.103

[clientes]
192.168.57.101
192.168.57.102
192.168.57.104
```

### **4. site.yml**  
```yaml
- hosts: tierra
  become: true
  tasks:
    - name: Instalar BIND9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Copiar configuración de named.conf.local
      copy:
        src: /vagrant/named.conf.local
        dest: /etc/bind/named.conf.local
        owner: root
        group: root
        mode: '0644'

    - name: Copiar configuración de named.conf.options
      copy:
        src: /vagrant/named.conf.options
        dest: /etc/bind/named.conf.options
        owner: root
        group: root
        mode: '0644'

    - name: Copiar archivo de zona db.sistema.sol
      copy:
        src: /vagrant/db.sistema.sol
        dest: /var/lib/bind/db.sistema.sol
        owner: bind
        group: bind
        mode: '0644'

    - name: Copiar archivo de zona inversa db.192.168.57
      copy:
        src: /vagrant/db.192.168.57
        dest: /var/lib/bind/db.192.168.57
        owner: bind
        group: bind
        mode: '0644'

    - name: Reiniciar el servicio DNS
      service:
        name: bind9
        state: restarted
        enabled: true

- hosts: clientes
  become: true
  tasks:
    - name: Configurar /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
      with_items:
        - "search sistema.sol"
        - "nameserver 192.168.57.103"

```

---

## 📋 PENDIENTE  
Tras probar el funcionamiento en la próxima clase, se actualizará el repositorio para incluir mejoras y resolver posibles problemas.

---
