### ISSUE TITLE
Test (comprobar DNS)

### ISSUE THREAD

**Issue by 22adrian22** [Almarchi/FTP-TEAM#2]
Hay que comprobarlo si necesito cambiar algo avisamelo y lo hare lo antes posible.

ACTUALIZACIÓN: Error en el archivo resolv.conf:

dig marte.sistema.sol (comando)
dig: parse of /etc/resolv.conf failed (resultado)

Vagrantfile modificado usado para la comprobación **no subirlo al repositorio**

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "tierra" do |dns|
    dns.vm.hostname = "tierra.sistema.sol"
    dns.vm.network :private_network, ip: "192.168.57.103"
    dns.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y bind9 bind9utils bind9-doc
    sudo cp /vagrant/named.conf.local /etc/bind/named.conf.local
    sudo cp /vagrant/named.conf.options /etc/bind/named.conf.options
    sudo cp /vagrant/db.sistema.sol /var/lib/bind/db.sistema.sol
    sudo cp /vagrant/db.192.168.57 /var/lib/bind/db.192.168.57
    sudo cp /vagrant/resolv.conf /etc/resolv.conf
    systemctl restart bind9
    systemctl enable bind9
  SHELL
  end

  config.vm.define "mercurio" do |mercurio|
    mercurio.vm.hostname = "mercurio.sistema.sol"
    mercurio.vm.network :private_network, ip: "192.168.57.101"
  end

  config.vm.define "venus" do |venus|
    venus.vm.hostname = "venus.sistema.sol"
    venus.vm.network :private_network, ip: "192.168.57.102"
  end

  config.vm.define "marte" do |marte|
    marte.vm.hostname = "marte.sistema.sol"
    marte.vm.network :private_network, ip: "192.168.57.104"
  end
end

**Comment by 22adrian22** [comment]
AÑADIRE EN ESTA ISSUE, los archivos correctos de servidor dns sin errores ademas de resolv.conf sin errores y mostrare el test y las pruebas realizas para demostrar su correcto funcionamiento

**Comment by 22adrian22** [comment]
# 🌐 Configuración de Servidor DNS BIND para el Dominio `sistema.sol`

Este documento describe los archivos de configuración, pruebas realizadas y resultados obtenidos al configurar un servidor DNS con BIND para el dominio `sistema.sol`. La configuración incluye resolución directa e inversa y está diseñada para un entorno con varias máquinas (`tierra`, `mercurio`, `venus` y `marte`).

---

## 📄 Configuraciones de Archivos

### **🗂 Archivo `db.sistema.sol`**

```dns
$TTL    604800
@       IN      SOA     tierra.sistema.sol. admin.sistema.sol. (
                            2         ; Serial
                            604800    ; Refresh
                            86400     ; Retry
                            2419200   ; Expire
                            604800 )  ; Negative Cache TTL

; Servidor de nombres principal
@       IN      NS      tierra.sistema.sol.

; Registros A para cada máquina
tierra      IN      A       192.168.57.103
mercurio    IN      A       192.168.57.101
venus       IN      A       192.168.57.102
marte       IN      A       192.168.57.104
```

**Explicación:**
- `SOA`: Define la autoridad principal del dominio, con su correo administrativo (convertido en `admin@sistema.sol`).
- `NS`: Apunta al servidor de nombres principal (`tierra.sistema.sol`).
- `A`: Mapea los nombres de las máquinas (`tierra`, `mercurio`, `venus`, `marte`) con sus respectivas direcciones IP.

---

### **🗂 Archivo `db.192.168.57`**

```dns
$TTL    604800
@       IN      SOA     tierra.sistema.sol. admin.sistema.sol. (
                            2         ; Serial
                            604800    ; Refresh
                            86400     ; Retry
                            2419200   ; Expire
                            604800 )  ; Negative Cache TTL

; Servidor de nombres principal
@       IN      NS      tierra.sistema.sol.

; Registros PTR para la resolución inversa
103     IN      PTR     tierra.sistema.sol.
101     IN      PTR     mercurio.sistema.sol.
102     IN      PTR     venus.sistema.sol.
104     IN      PTR     marte.sistema.sol.
```

**Explicación:**
- `PTR`: Realiza la resolución inversa, asociando direcciones IP con nombres de dominio.

---

### **⚙️ Archivo `named.conf.local`**

```conf
zone "sistema.sol" {
    type master;
    file "/var/lib/bind/db.sistema.sol";
};

zone "57.168.192.in-addr.arpa" {
    type master;
    file "/var/lib/bind/db.192.168.57";
};
```

**Explicación:**
- Declara las zonas de configuración para:
  - Resolución directa (`sistema.sol`).
  - Resolución inversa (`57.168.192.in-addr.arpa`).

---

### **⚙️ Archivo `named.conf.options`**

```conf
options {
    directory "/var/cache/bind";

    forwarders {
        1.1.1.1;
    };

    dnssec-validation no;
    listen-on { any; };
    listen-on-v6 { any; };
    allow-query { any; };
};
```

**Explicación:**
- `forwarders`: Configura el reenviador DNS (en este caso, `1.1.1.1`).
- `dnssec-validation no`: Desactiva la validación DNSSEC.
- `allow-query { any; }`: Permite consultas desde cualquier IP.

---

### **📄 Archivo `resolv.conf`**

```conf
nameserver 192.168.57.103
search sistema.sol
```

**Explicación:**
- `nameserver`: Define la dirección IP del servidor DNS para la resolución de nombres.
- `search`: Especifica el dominio predeterminado (`sistema.sol`) para consultas DNS incompletas.

---

## ✅ Comandos de Verificación y Resultados

### **🖥 Verificar Servidor**

#### Comando 1: `nslookup mercurio.sistema.sol` (En `tierra`)
```bash
vagrant@tierra:~$ nslookup mercurio.sistema.sol
Server:         192.168.57.103
Address:        192.168.57.103#53

Name:   mercurio.sistema.sol
Address: 192.168.57.101
```
**Objetivo**: Validar la resolución directa del nombre `mercurio.sistema.sol` a su dirección IP.

#### Comando 2: `nslookup 192.168.57.101` (En `tierra`)
```bash
vagrant@tierra:~$ nslookup 192.168.57.101
101.57.168.192.in-addr.arpa     name = mercurio.sistema.sol.
```
**Objetivo**: Confirmar la resolución inversa de la IP `192.168.57.101` al nombre `mercurio.sistema.sol`.

---

### **💻 Verificar Clientes**

#### Cliente `mercurio`

1. `nslookup tierra.sistema.sol`
   ```bash
   vagrant@mercurio:~$ nslookup tierra.sistema.sol
   Server:         192.168.57.103
   Address:        192.168.57.103#53

   Name:   tierra.sistema.sol
   Address: 192.168.57.103
   ```
   **Objetivo**: Comprobar que el cliente puede resolver el nombre `tierra.sistema.sol`.

2. `nslookup mercurio`
   ```bash
   vagrant@mercurio:~$ nslookup mercurio
   Server:         192.168.57.103
   Address:        192.168.57.103#53

   Name:   mercurio.sistema.sol
   Address: 192.168.57.101
   ```
   **Objetivo**: Validar que el cliente puede resolver su propio nombre a través del servidor DNS.

3. `nslookup 192.168.57.103`
   ```bash
   vagrant@mercurio:~$ nslookup 192.168.57.103
   103.57.168.192.in-addr.arpa     name = tierra.sistema.sol.
   ```
   **Objetivo**: Verificar la resolución inversa de `192.168.57.103`.

#### Clientes `venus` y `marte`
*Los comandos y resultados son equivalentes a los de `mercurio`, confirmando la coherencia de la configuración.*

---

## ⚙️ Automatización de Inclusión de Archivos con `site.yml`

Para incluir los archivos en las máquinas correspondientes, se utiliza el archivo Ansible Playbook `site.yml`.

### **Contenido del Archivo `site.yml`**

```yaml
---
- hosts: tierra
  become: true
  tasks:
    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar Bind9 y utilidades
      apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
        state: present

    - name: Copiar el archivo named.conf.local desde la máquina remota
      copy:
        src: /vagrant/named.conf.local
        dest: /etc/bind/named.conf.local
        remote_src: yes

    - name: Copiar el archivo named.conf.options desde la máquina remota
      copy:
        src: /vagrant/named.conf.options
        dest: /etc/bind/named.conf.options
        remote_src: yes

    - name: Copiar la zona db.sistema.sol desde la máquina remota
      copy:
        src: /vagrant/db.sistema.sol
        dest: /var/lib/bind/db.sistema.sol
        owner: bind
        group: bind
        mode: '0644'
        remote_src: yes

    - name: Copiar la zona db.192.168.57 desde la máquina remota
      copy:
        src: /vagrant/db.192.168.57
        dest: /var/lib/bind/db.192.168.57
        owner: bind
        group: bind
        mode: '0644'
        remote_src: yes

    - name: Configurar resolv.conf desde la máquina remota
      copy:
        src: /vagrant/resolv.conf
        dest: /etc/resolv.conf
        remote_src: yes

    - name: Reiniciar el servicio Bind9
      service:
        name: bind9
        state: restarted

- hosts: clientes
  become: true
  tasks:
    - name: Configurar resolv.conf en clientes
      copy:
        src: /vagrant/resolv.conf
        dest: /etc/resolv.conf
        remote_src: yes
```

### **Ejecución del Archivo `site.yml`**

Para ejecutar este playbook y aplicar las configuraciones, utiliza el siguiente comando desde el directorio donde se encuentra el archivo `site.yml`:

```bash
ansible-playbook -i inventory.yml site.yml
```

**Nota:** Asegúrate de que las máquinas objetivo estén configuradas correctamente en el inventario de Ansible (`hosts`), con acceso SSH habilitado y las claves necesarias distribuidas.
