### ISSUE TITLE
Uso del cliente FTP en línea de comandos

### ISSUE THREAD

**Issue by 22adrian22** [Almarchi/FTP-TEAM#4]
Se espera automatizar los tre sprimeros pasos de la tarea con un archivo ansible, y demostrar el uso de comandos y herramientas necesarias para resolver el resto de puntos del apartado

**Comment by 22adrian22** [comment]
A continuacion dejo la documentacion completa para realizar este punto, escribid si estais de acuerdo con todo o si veis algo, si lo probais mejor :), cuando digais cerramos esta issue

**Comment by 22adrian22** [comment]
# 🖥️ Guía para el Uso del Cliente FTP en Línea de Comandos

## 📂 **Automatización de Tareas Iniciales con Ansible**

Los primeros tres pasos del proceso se automatizan utilizando un archivo Ansible Playbook llamado `ftp_playbook.yml`.

### **Tareas Automatizadas**:

1️⃣ Crear el usuario `pepe` (si no existe).
2️⃣ Crear el directorio `/home/pepe/pruebasFTP` y moverse a él.
3️⃣ Crear el archivo `datos1.txt` dentro del directorio `pruebasFTP` con contenido predeterminado.

### **Contenido del Archivo `ftp_playbook.yml`**:

```yaml
---
- name: Uso del cliente FTP en línea de comandos
  hosts: tierra
  become: yes
  tasks:
    - name: Crear usuario pepe si no existe
      user:
        name: pepe
        state: present
        create_home: yes

    - name: Crear directorio /home/pepe/pruebasFTP
      file:
        path: /home/pepe/pruebasFTP
        state: directory
        owner: pepe
        group: pepe
        mode: '0755'

    - name: Cambiar al directorio pruebasFTP
      ansible.builtin.shell: cd /home/pepe/pruebasFTP

    - name: Crear archivo datos1.txt con contenido
      ansible.builtin.copy:
        content: |
          Este es un archivo de prueba para el FTP.
        dest: /home/pepe/pruebasFTP/datos1.txt
        owner: pepe
        group: pepe
        mode: '0644'
```

### **Ejecución del Playbook**:

Para ejecutar este archivo, utiliza el siguiente comando:

```bash
ansible-playbook -i inventory.yml ftp_playbook.yml
```

## 📋 **Pasos Manuales**

Los pasos restantes deben realizarse manualmente, ya que no se pueden automatizar con Ansible. A continuación, se describen las tareas junto con los comandos necesarios.

### 4️⃣ **Conectar al servidor FTP en modo anónimo**

Instala el cliente FTP si aún no lo tienes:

```bash
sudo apt install ftp
```

Conéctate al servidor FTP:

```bash
ftp ftp.cica.es
```

Cuando se te solicite, ingresa:

- **Usuario**: `anonymous`
- **Contraseña**: (presiona Enter)

![Image](https://github.com/user-attachments/assets/24cc1efd-403b-4808-9108-79763f38ba54)

### 5️⃣ **Examinar el directorio activo en el servidor**

Ejecuta:

```bash
pwd
```

Esto mostrará la ruta activa en el servidor.

![Image](https://github.com/user-attachments/assets/53593f11-302b-4f7e-8f98-18b2bd976da4)

### 6️⃣ **Examinar el directorio activo en el cliente**

Desde la sesión FTP, utiliza:

```bash
!pwd
```

![Image](https://github.com/user-attachments/assets/00b6375f-1a02-4914-a763-bc2b79de88c3)

### 7️⃣ **Listar los archivos del servidor**

Ejecuta:

```bash
ls
```

![Image](https://github.com/user-attachments/assets/34fd692c-1ec9-4c84-a5b5-b9c4378e9ec8)

### 8️⃣ **Listar los archivos en la carpeta del cliente**

Para listar los archivos locales:

```bash
!ls
```

![Image](https://github.com/user-attachments/assets/7d8c4a7d-7116-44cb-b474-356b9e778d07)

### 9️⃣ **Descargar el archivo `/pub/check` del servidor**

Navega al directorio y descarga el archivo:

```bash
cd /pub
get check
```

**Nota**: Antes de conectarte al servidor (paso 4), ejecuta `sudo su` para obtener permisos de administrador.

![Image](https://github.com/user-attachments/assets/d99d516b-656c-429c-9eb4-e46832680563)

### 🔠 **Comprobar que se ha descargado el archivo**

Verifica si el archivo está en tu máquina local:

```bash
!ls
```

![Image](https://github.com/user-attachments/assets/1d1d21b5-91df-4366-bf13-f85aa77e8955)

Busca el archivo `check` en la lista.

### 1️⃣1️⃣ **Crear el directorio "imágenes" dentro de `pruebasFTP` y comprobar**

Crea el directorio localmente desde el cliente FTP:

```bash
!mkdir /home/pepe/pruebasFTP/imagenes
```

Verifica que se haya creado correctamente:

```bash
!ls /home/pepe/pruebasFTP
```

![Image](https://github.com/user-attachments/assets/dc80571f-dd88-4efe-8f05-d9cee4e04784)

### 1️⃣2️⃣ **Subir el archivo `datos1.txt` al servidor**

Desde la sesión FTP, intenta subir el archivo:

```bash
put datos1.txt
```

**Nota**: Si falla, podría ser porque la cuenta anónima no tiene permisos de escritura en el servidor.

En este caso falló:

![Image](https://github.com/user-attachments/assets/4bc5621f-b943-45bb-9ea3-925b0bf7507d)

### 1️⃣3️⃣ **Cerrar la conexión con el servidor**

Para finalizar la sesión FTP, utiliza:

```bash
bye
```

![Image](https://github.com/user-attachments/assets/a3ae038d-7fe8-4000-bdec-e58b038efb59)

---
